# Generated by Django 6.0.8 on 2026-10-05 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('type', models.CharField(db_index=True, max_length=32)),
                ('version', models.CharField(blank=True, default='', max_length=32)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('description', models.TextField()),
                ('size', models.BigIntegerField()),
                ('added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('origin', models.CharField(choices=[('upload', 'uploaded'), ('url', 'fetched from a URL'), ('import', 'came with an imported world'), ('tool', 'made by a tool'), ('export', 'exported from a world here'), ('folder', 'put in the shared folder by hand')], max_length=16)),
                ('source', models.TextField(blank=True, default='')),
                ('author', models.CharField(blank=True, default='', max_length=200)),
                ('licence', models.CharField(blank=True, default='', max_length=200)),
                ('made_with', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('present', 'present'), ('missing', 'missing')], default='present', max_length=16)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_added', to=settings.AUTH_USER_MODEL)),
                ('charged_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_charged', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added'],
            },
        ),
    ]
